### ISSUE TITLE
GridFSOutputStream

### ISSUE THREAD

**Issue by ashertarno** [st-h/vertx-mongo-streams#1]
do you have an implementation also for reading files FROM gridfs into vert.x readstream? thanks.

**Comment by st-h** [comment]
I've been doing this, but I am on the road this week. I'll get back when I am able to have a look. But it wasn't much trouble. The mongo driver examples were quite helpful there, in case you haven't noticed those.
But please don't cross post or at least provide a reference, so that other people don't have to do the same work all over again.

**Comment by ashertarno** [comment]
hey, thanks for a prompt response.
