### ISSUE TITLE
Current implementation seems to writes incorrect data in multithreaded context

### ISSUE THREAD

**Issue by st-h** [st-h/vertx-mongo-streams#11]
I wrote a concurrency test to validate issues with the old implementation, which also shows that current implementation seems to writes incorrect data. I added the old implementation with an added set of synchronized blocks and the concurrency test together to branch `concurrency`. The old implementation passes the test, whereas the new fails.

**Comment by antofar** [comment]
You are right, I was releasing the lock too early, thanks for taking the time to write the test, I should have written it before the first PR.

In case the incoming buffer has content left after draining it into the output buffer, we put the remaining content into the internal queue. This last step was out of the synchronisation block but it should be inside since the internal queue can be accessed concurrently (basically this was part of the initial problem).
I am sending you a PR for the fix.

**Comment by st-h** [comment]
Thank you. Merged and released as 1.2.0. Actually I should have bumped to 1.2.x quite a bit earlier...
